### ISSUE TITLE
Input border corners not rounded

### ISSUE THREAD

**Issue by gchan** [hyspace/typeahead.js-bootstrap3.less#10]
Not sure if this is an issue on my end or an edge case for the CSS file.

My HTML is currently like this:

``` html
<div class="input-group">
  <input class="form-control" id="q" name="q" placeholder="Search" type="text">
  <span class="input-group-btn">
    <button class="btn btn-primary" type="button">
      <span class="glyphicon glyphicon-search"></span>
    </button>
  </span>
</div>
```

What I'm currently getting is this:
![screen shot 2014-06-02 at 6 03 17 pm](https://cloud.githubusercontent.com/assets/1182969/3144214/bb446b04-ea1b-11e3-83be-e563b71b219d.png)

When what I really want is this:
![screen shot 2014-06-02 at 6 03 50 pm](https://cloud.githubusercontent.com/assets/1182969/3144215/c616ea52-ea1b-11e3-9f95-669bac899020.png)

It looks like this Bootstrap style rule:

``` css
.input-group .form-control:not(:first-child):not(:last-child) {
  border-radius: 0;
}
```

...is taking precedence over this rule:

``` css
.input-group .twitter-typeahead:first-child .tt-input {
  border-bottom-left-radius: 4px;
  border-top-left-radius: 4px;
}
```

It doesn't help if I import the typeahead.css file first (ahead of Bootstrap's files)

I had to modify the typeahead.css file to include the .form-control class as a quick fix.

``` css
.input-group .twitter-typeahead:first-child .tt-input.form-control  {
  border-bottom-left-radius: 4px;
  border-top-left-radius: 4px;
}
```

I wonder if there is more elegant solution to my problem.
