### ISSUE TITLE
Layout problem with form-inline class

### ISSUE THREAD

**Issue by ahocquet** [hyspace/typeahead.js-bootstrap3.less#11]
Hi,

I have an issue when using this style within a form-inline. The typeahead input inserts a kind of line break and isn't displayed next to the label :

![image](https://cloud.githubusercontent.com/assets/1451308/3424138/be903054-ffbf-11e3-8190-78c0ed81c851.png)

So, I added a css rule to fix it. But i'm not a css guru at all, and it's surely doesn't respect CSS coding best practices.

``` css
.form-inline .twitter-typeahead {
    width: auto;
    float: none;
}
```

![image](https://cloud.githubusercontent.com/assets/1451308/3424153/78654e56-ffc0-11e3-9ef4-ceb9d203d77a.png)

It almost does the trick. The last problem is that the label is not vertically aligned in the middle. Adding a vertical-align property to the css rule made the trick :

``` css
.form-inline .twitter-typeahead {
    width: auto;
    float: none;
    vertical-align: middle;
}
```

![image](https://cloud.githubusercontent.com/assets/1451308/3424158/ad946210-ffc0-11e3-98a0-661f753cf30c.png)

Once again, I'm not a css expert at all. It's just a dirty quick fix to fit my needs. I'm looking forward to see a proper solution :)

Sorry for the english, it's not my native language. Do not hesitate to correct my typos :)

Aixki
